CREATE TABLE type1_student (
    STUDENTID INT PRIMARY KEY,
    FIRSTNAME NVARCHAR(50),
    LASTNAME NVARCHAR(50),
    BIRTHDATE DATE,
    ADDRESS NVARCHAR(100),
    INSERTTIMESTAMP DATETIME,
    UPDATETIMESTAMP DATETIME
);
